#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKEND_DIR="${BACKEND_DIR:-$ROOT_DIR/../seng3011-tango-apis}"
BACKEND_ENV_FILE="${BACKEND_ENV_FILE:-$BACKEND_DIR/.localstack-api.env}"

if [[ ! -f "$BACKEND_ENV_FILE" ]]; then
  echo "Missing $BACKEND_ENV_FILE"
  echo "Run the backend LocalStack deploy first:"
  echo "  cd \"$BACKEND_DIR\" && docker compose up -d && bash scripts/localstack-cdk-deploy.sh"
  exit 1
fi

if command -v rg >/dev/null 2>&1; then
  BASE_LINE="$(rg -m1 -o '^BASE=.*' "$BACKEND_ENV_FILE" || true)"
else
  BASE_LINE="$(grep -E '^BASE=' "$BACKEND_ENV_FILE" | head -n 1 || true)"
fi
if [[ -z "${BASE_LINE}" ]]; then
  echo "Couldn't find BASE=... in $BACKEND_ENV_FILE"
  exit 1
fi

BASE="${BASE_LINE#BASE=}"
if [[ -z "${BASE}" ]]; then
  echo "BASE was empty in $BACKEND_ENV_FILE"
  exit 1
fi

OUT_FILE="$ROOT_DIR/.env.local"
cat >"$OUT_FILE" <<EOF
# Auto-generated by scripts/localstack-sync-env.sh
TANGO_API_BASE_URL=${BASE}
EOF

echo "Wrote $OUT_FILE"
echo "TANGO_API_BASE_URL=$BASE"
